version: '3'

services:
  db:
    image: postgres

  server:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./borrow_me
      dockerfile: Dockerfile.server
    command: bash scripts/start-server.sh
    volumes:
      - ./borrow_me/:/server/
    ports:
      - "8000:8000"
    depends_on:
      - db
