version: '3'

services:
  db:
    image: postgres

  server:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./server
      dockerfile: Dockerfile.server
    command: bash scripts/start-server.sh
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    command: sh -c ""
    volumes:
      - ./frontend:/frontend
    ports:
      - "8080:8080"
    depends_on:
      - server