# Use python:2.7.14 as the base Docker image
FROM python:2.7.14

# Set current working directory in the container
WORKDIR /server

# Copy requirements into the docker container
COPY requirements.txt .

# Install required Python packages
RUN pip install -r requirements.txt

# Copy the contents of the current working directory to the container
ADD . /server

# Install Postgres client to check when the DB is ready for use
RUN apt-get update
RUN apt-get install -f -y postgresql-client
